discussion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

todolist/urls.py
from django.urls import path

from . import views

#path() function
#path(route, view, name)
app_name = 'todolist'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	# /todolist/register
	path('register', views.register, name="register"),
	# /todolist/change_password
	path('change_password', views.change_password, name='change_password'),
	# /todolist/login
	path('login', views.login_view, name='login'),
	# /todolist/logout
	path('logout', views.logout_view, name="logout"),
	# /todolist/add_task
	path('add_task', views.add_task, name='add_task'),
	# /todolist/add_event
	path('add_event', views.add_event, name='add_event'),
	# /todolist/update_profile
	path('update_profile', views.update_profile, name='update_profile'),
	# /todolist/<todoitem_id>/edit
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	# /todolist/<todoitem_id>/delete
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

todolist/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

class RegisterForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	first_name = forms.CharField(label='First Name', max_length=20)
	last_name = forms.CharField(label='Last Name', max_length=20)
	password = forms.CharField(label='Password', max_length=20)
	confirm_password = forms.CharField(label='Confirm Password', max_length=20)

todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
#from django.http import HttpResponse
from .models import ToDoItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone
# 'from' keyword allows importing of necessary classes, methods and other items needed in our application. While 'import' keyword defines what we are importing from the package

# Create your views here.
def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	context = {
		'todoitem_list': todoitem_list,
		'user': request.user
	}
	return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

def register(request):
	users = User.objects.all()
	is_user_registered = False
	context = {
		"is_user_registered": is_user_registered
	}

	for indiv_user in users:
		if indiv_user.username == "johndoe":
			is_user_registered = True
			break


	if is_user_registered == False:
		user = User()
		user.username = "johndoe"
		user.first_name = "John"
		user.last_name = "Doe"
		user.email = "john@mail.com"
		user.set_password("john1234")
		user.is_staff = False
		user.is_active = True
		user.save()
		context ={
			"first_name": user.first_name,
			"last_name": user.last_name
		}

	return render(request, "todolist/register.html", context)

def change_password(request):

	is_user_authenticated = False

	user = authenticate(username="johndoe", password="john1234")
	print(user)
	if user is not None:
		authenticated_user = User.objects.get(username='johndoe')
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True
		context = {
			"is_user_authenticated": is_user_authenticated
		}

		return render(request, "todolist/change_password.html", context)

def login_view(request):
	context = {}

	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid() == False:
			form = LoginForm()

		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			context = {
				"username": username,
				"password": password
			}

			if user is not None:
				login(request, user)
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}

	return render(request, "todolist/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):
	context = {
       "user": request.user
    }

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name=task_name)

			if not duplicates:
				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
				return redirect('todolist:index')

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)

def add_event(request):
		context = {
	       "user": request.user
	    }

		if request.method == 'POST':
			form = AddEventForm(request.POST)

			if form.is_valid() == False:
				form = AddEventForm()
			else:
				event_name = form.cleaned_data['event_name']
				description = form.cleaned_data['description']

				duplicates = ToDoItem.objects.filter(event_name=event_name)

				if not duplicates:
					ToDoItem.objects.create(event_name=event_name, description=description, date_created=timezone.now(), user_id=request.user.id)
					return redirect('todolist:index')

				else:
					context = {
						"error": True
					}

		return render(request, "todolist/add_event.html", context)

def update_profile(request, todoitem_id):

		todoitem = ToDoItem.objects.filter(pk=todoitem_id)

		context = {
			"user": request.user,
			"todoitem_id": todoitem_id,
			"update_profile": todoitem[0].update_profile
		}

		if request.method == 'POST':
			form = UpdateProfileForm(request.POST)

			if form.is_valid() == False:
					form = UpdateProfileForm()
			else:
				update_profile = form.cleaned_data['update_profile']

				if todoitem:
					todoitem[0].update_profile = update_profile

					todoitem[0].save()
					return redirect("todolist:index")
				else:
					context = {
						"error": True
					}

		return render(request, "todolist/update_profile.html", context)

def update_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status
	}

	if request.method == 'POST':
		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:
			form = UpdateTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}

	return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}To Do App{% endblock%}</title>

	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
 
</head>
<body>
	{% include "navbar.html" %}

	{% block content%}
	{% endblock %}

	<!-- Bootstrap -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">To Do App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="add_task">Add Task</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="add_event">Add Event</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="update_profile">Update Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="register">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="logout">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add Event</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate Event found</p>
				{% endif %}
				<form action="{% url 'todolist:add_event' %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
					    <label for="event_name">Event Name: </label>
					    <input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
					    <label for="description">Description: </label>
					    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Add Event">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1>You are not authorized to access this page.</h1>
		<p>Kindly login <a href="{% url 'todolist:login'%}">here</a></p>
	{% endif %}
{% endblock %}

todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add A Task</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate task found</p>
				{% endif %}
				<form action="{% url 'todolist:add_task' %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
					    <label for="task_name">Task Name: </label>
					    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
					    <label for="description">Description: </label>
					    <textarea class="form-control" name="description" value="{{ description }}" required></textarea>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Add Task">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1>You are not authorized to access this page.</h1>
		<p>Kindly login <a href="{% url 'todolist:login'%}">here</a></p>
	{% endif %}
{% endblock %}

todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid user credentials</h1>
	<p>A duplicate user has been found, user creation unsuccessfull</p>
{% else %}
	<h1>User password successfully updated</h1>
	<p>The password has been successfully updated</p>
{% endif %}

todolist/templates/todolist/index.html
{% extends 'base.html'%}

{% block title %}Home{% endblock %}

{% block content%}
    {% if todoitem_list and user.is_anonymous == False  %}
        <h1 class="text-center my-3">Welcome {{ user.first_name }} {{user.last_name}}!</h1>
        <div class="container">
            <div class="row">
                <h3 class="text-center mb-3">My Tasks</h3>
                <ul class="list-group col-lg-2 offset-lg-5 text-center">
                {% for todoitem in todoitem_list %}
                    <a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">
                        <li class="list-group-item">{{ todoitem.task_name }}</li>
                    </a>
                {% endfor %}
                </ul>
            </div> 
        </div>
    {% elif user.is_anonymous == True %}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
    {% else %}
        <p class="text-center">No tasks have been created</p>
    {% endif %}
{% endblock%}

todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock%}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Login</h1>
				{% if error == True %}
					<p class="text-danger">Invalid user credentials, please check your username and password</p>
				{% endif %}
				<form action="{% url 'todolist:login' %}" method="post">
					<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
					<!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
					{% csrf_token %}

					<div class="mb-3">
					    <label for="username">Username: </label>
					    <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
					</div>

					<div class="mb-3">
					    <label for="password">Password: </label>
					    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Login">
					</div>

				</form>
			</div>
		</div>
	</div>

{% endblock %}

todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock%}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Register</h1>
				{% if is_user_registered == False %}
					<h1 class="text-center">Duplicate User Found</h1>
					<p class="text-center">A duplicate user has been found, user creation unsuccessful</p>
				{% endif %}
				<form action="{% url 'todolist:is_user_registered' %}" method="post">
					<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
					<!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
					{% csrf_token %}

					<div class="mb-3">
					    <label for="username">Username: </label>
					    <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
					</div>
					<div class="mb-3">
					    <label for="first_name">First Name: </label>
					    <input class="form-control" id="first_name" type="text" name="first_name" value="{{ first_name }}" maxlength="20" required>
					</div>
					<div class="mb-3">
					    <label for="last_name">Last Name: </label>
					    <input class="form-control" id="last_name" type="text" name="last_name" value="{{ last_name }}" maxlength="20" required>
					</div>
					<div class="mb-3">
					    <label for="email">Email: </label>
					    <input class="form-control" id="email" type="text" name="email" value="{{ email }}" maxlength="20" required>
					</div>
					<div class="mb-3">
					    <label for="password">Password: </label>
					    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
					</div>
					<div class="mb-3">
					    <label for="password">Confirm Password: </label>
					    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Register">
					</div>

				</form>
			</div>
		</div>
	</div>
{% else %}
	<h1>User Successfully Created!</h1>
	<p>The account for {{first_name}} {{last_name}} has been successfully created</p>
{% endif %}
{% endblock %}

todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}Update{% endblock %}

{% block content%}
	<div class="text-center my-3">
		<h1>{{ task_name }}</h1>
		<h3>Description</h3>
		<p>{{ description }}</p>
		<h3>Status</h3>
		<p>{{ status }}</p>
		
		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
		</button>

		<button class="btn btn-danger mx-1 text-decoration-none">
			<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
		</button>

		<button class="btn btn-warning mx-1 text-decoration-none">
			<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
		</button>
		
	</div>
{% endblock %}

todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content%}
	{% if user.is_anonymous == False%}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Update Task</h1>
					{% if error == True %}
						<p class="text-danger">Task not found</p>
					{% endif %}
					<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
						    <label for="task_name">Task Name: </label>
						    <input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="description">Description: </label>
						    <textarea class="form-control" name="description" required>{{ description }}</textarea>
						</div>

						<div class="mb-3">
						    <label for="status">Status: </label>
						    <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
						</div>

						<div class="text-center">
					    	<input class="btn btn-success" type="submit" value="Update Task">
						</div>

					</form>
				</div>
			</div>
		</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock%}